inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Lint/EmptyClass:
  Exclude:
    - "spec/fixtures/class_without_sig.rb"
    - "spec/fixtures/class_with_sig.rb"

Metrics/BlockLength:
  Exclude:
    - "kontainer.gemspec"
    - "spec/**/*_spec.rb"

Naming/MethodParameterName:
  AllowedNames:
    - "as"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
