name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

permissions: {}

jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
#          - '2.7.3'
#          - '3.0.3'`
          - '3.1.0'
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v2
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run rubocop
      run: bundle exec rubocop
    - name: Run the default task
      run: bundle exec rake
